name: money_planner
description: "Money Planner"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # JSON
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

  # NETWORK
  dio: ^5.7.0
  retrofit: ^4.4.0
  logger: ^2.4.0  # for logging purpose

  # DI
  injectable: ^2.5.0
  get_it: 

  # BLOC
  flutter_bloc: ^8.1.6

  # ENV
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.13

  retrofit_generator: ^9.0.0

  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - .env